[phases.setup]
nixPkgs = ['php83', 'php83Packages.composer']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-interaction']

[phases.build]
cmds = [
    'php artisan config:clear',
    'php artisan cache:clear',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
```

### **5. ELIMINA la variable PORT de Railway:**

En Railway → Variables → **Elimina**:
```
PORT="8000"  ← BORRAR ESTA